apiVersion: v1
kind: Pod
metadata:
  name: ebs-test
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: /data
      name: ebs-storage

  volumes:
  - name: ebs-storage
    persistentVolumeClaim:
      claimName: test-ebs